#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Dart sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The Dart app container.
  dart:
    # https://hub.docker.com/_/dart
    image: dart:latest
    container_name: ${APP_CONTAINER_NAME:-dart_app}
    networks:
      - local
    stdin_open: true
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Run the Dart app container Shell.
    command: ["/bin/sh"]

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-dart_local}"
