#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Ionic sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The Ionic app container.
  ionic:
    # Build the Docker image from the Dockerfile.
    build:
      context: '.'
    image: ionic:latest
    container_name: ${APP_CONTAINER_NAME:-ionic_app}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:${APP_PORT:-80}
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Start the Ionic CLI dev server.
    # https://ionicframework.com/docs/developing/previewing
    command: [
      "ionic", "serve",
      "--host", "0.0.0.0",
      "--port", "${APP_PORT:-80}"
    ]

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-ionic_local}"
