#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the WordPress sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The WordPress app container.
  wordpress:
    # https://hub.docker.com/_/wordpress
    image: wordpress:latest
    container_name: ${APP_CONTAINER_NAME:-wordpress_app}
    depends_on:
      - mysql
    # Environment variables honoured in custom wp-config.php
    # https://github.com/docker-library/wordpress/blob/master/wp-config-docker.php
    environment:
      WORDPRESS_DEBUG: true
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: "${DB_USERNAME}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_DATABASE:-wordpress}"
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - .${CODE_DIR:-/code}:/var/www/html

  # The MySQL database container.
  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql:latest
    container_name: ${DB_CONTAINER_NAME:-wordpress_db}
    # https://hub.docker.com/_/mysql
    # Go to Environment variables.
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-wordpress}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root"]
      retries: 3
      timeout: 5s
    networks:
      - local
    platform: linux/x86_64
    # Map the database container exposed port to the host port.
    ports:
     - ${DB_PORT:-3306}:3306
    volumes:
      - mysql_data:/var/lib/mysql

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-wordpress_local}"

# The Docker volumes.
volumes:
  mysql_data:
    driver: "local"
    name: "${DB_VOLUME_NAME:-wordpress_db_data}"
