#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Ackee sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The Ackee app container.
  ackee:
    # https://hub.docker.com/_/node
    image: node:18
    container_name: ${APP_CONTAINER_NAME:-ackee_app}
    depends_on:
      - mongodb
    # https://github.com/electerious/Ackee/blob/master/docs/Options.md
    environment:
      ACKEE_USERNAME: "${ACKEE_USERNAME}"
      ACKEE_PASSWORD: "${ACKEE_PASSWORD}"
      ACKEE_MONGODB: mongodb://mongodb:27017/${MONGO_DATABASE:-ackee}
      ACKEE_ALLOW_ORIGIN: "*"
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:3000
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    command: ["yarn", "start"]

  # The MongoDB database container.
  mongodb:
    # https://hub.docker.com/_/mongo
    image: mongo:latest
    container_name: "${MONGO_CONTAINER_NAME:-ackee_mongodb}"
    # https://hub.docker.com/_/mongo
    # Go to Configuration -> Environment variables.
    environment:
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE:-ackee}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      retries: 3
      timeout: 5s
    networks:
      - local
    # Map the database container exposed port to the host port.
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - mongodb_data:/data/db

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-ackee_local}"

# Docker volumes
volumes:
  mongodb_data:
    driver: "local"
    name: "${MONGO_VOLUME_NAME:-ackee_mongodb_data}"
