#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the AdonisJS sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The AdonisJS app container.
  adonisjs:
    # https://hub.docker.com/_/node
    image: node:18
    container_name: ${APP_CONTAINER_NAME:-adonisjs_app}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:3333
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Start the AdonisJS CLI dev server.
    # https://docs.adonisjs.com/guides/installation#starting-the-development-server
    command: ["node", "ace", "serve", "--watch"]

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-adonisjs_local}"
