#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Docusaurus sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The Docusaurus app container.
  docusaurus:
    # https://hub.docker.com/_/node
    image: node:18-alpine
    container_name: ${APP_CONTAINER_NAME:-docusaurus_app}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:${APP_PORT:-80}
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Start The Docusaurus CLI dev server
    # https://docusaurus.io/docs/cli#docusaurus-start-sitedir
    command: [
      "yarn", "run", "start",
      "--port", "${APP_PORT:-80}",
      "--host", "0.0.0.0"
    ]

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-docusaurus_local}"
