#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the NestJS sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The NestJS app container.
  nestjs:
    # Build the Docker image from the Dockerfile.
    build:
      context: '.'
    image: nestjs:latest
    container_name: ${APP_CONTAINER_NAME:-nestjs_app}
    networks:
      - local
    ports:
      - ${APP_PORT:-80}:3000
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Start the NestJS CLI dev server.
    # https://docs.nestjs.com/cli/usages#nest-start
    command: ["yarn", "run", "start:dev"]

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-nestjs_local}"
