#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Gatsby sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# The Docker services.
services:
  # The Gatsby app container.
  gatsby:
    # Build the Docker image from the Dockerfile.
    build:
      context: '.'
    image: gatsby:latest
    container_name: ${APP_CONTAINER_NAME:-gatsby_app}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:${APP_PORT:-80}
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Start the Gatsby CLI dev server.
    # https://www.gatsbyjs.com/docs/reference/gatsby-cli/
    command: [
      "gatsby", "develop",
      "-H", "0.0.0.0",
      "-p", "${APP_PORT:-80}"
    ]

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-gatsby_local}"
