#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Nuxt sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# The Docker services.
services:
  # The Nuxt app container.
  nuxt:
    # https://hub.docker.com/_/node
    image: node:16-alpine
    container_name: ${APP_CONTAINER_NAME:-nuxt_app}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:${APP_PORT:-80}
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Start the Nuxt dev server.
    # https://nuxtjs.org/docs/get-started/commands/#list-of-commands
    command: [
      "yarn", "run", "dev",
      "--port", "${APP_PORT:-80}",
      "--hostname", "0.0.0.0"
    ]

# Docker networks
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-nuxt_local}"
