#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Apache sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The Apache app container
  apache:
    # https://hub.docker.com/_/httpd
    image: httpd:alpine
    container_name: ${APP_CONTAINER_NAME:-apache_app}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - .${CODE_DIR:-/code}:/usr/local/apache2/htdocs
      - .${CONFIG_DIR:-/config}/httpd.conf:/usr/local/apache2/conf/httpd.conf

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-apache_local}"
