#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Drupal sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The Drupal app container.
  drupal:
    # https://hub.docker.com/r/bitnami/drupal
    image: bitnami/drupal:latest
    container_name: ${APP_CONTAINER_NAME:-drupal_app}
    depends_on:
      - mariadb
    # https://hub.docker.com/r/bitnami/drupal
    # Go to Configuration -> Environment variables.
    environment:
      DRUPAL_SITE_NAME: "${APP_NAME:-drupal}"
      DRUPAL_USERNAME: "${DRUPAL_USER}"
      DRUPAL_PASSWORD: "${DRUPAL_PASSWORD}"
      DRUPAL_EMAIL: "${DRUPAL_EMAIL}"
      DRUPAL_DATABASE_HOST: mariadb
      DRUPAL_DATABASE_NAME: "${DB_DATABASE:-drupal}"
      DRUPAL_DATABASE_USER: "${DB_USERNAME}"
      DRUPAL_DATABASE_PASSWORD: "${DB_PASSWORD}"
      ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:8080
    volumes:
      - .${CODE_DIR:-/code}:/bitnami/drupal

  # The MariaDB database container.
  mariadb:
    # https://hub.docker.com/_/mariadb
    image: mariadb:latest
    container_name: "${DB_CONTAINER_NAME:-drupal_db}"
    # https://hub.docker.com/_/mariadb
    # Go to Environment variables.
    environment:
      MARIADB_DATABASE: "${DB_DATABASE:-drupal}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root"]
      retries: 3
      timeout: 5s
    networks:
      - local
    # Map the database container exposed port to the host port.
    ports:
     - "${DB_PORT:-3306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-drupal_local}"

# The Docker volumes.
volumes:
  mariadb_data:
    driver: "local"
    name: "${DB_VOLUME_NAME:-drupal_db_data}"
