#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Astro sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The Astro app container.
  astro:
    # https://hub.docker.com/_/node
    image: node:latest
    container_name: ${APP_CONTAINER_NAME:-astro_app}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:${APP_PORT:-80}
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Start the Astro CLI dev server.
    # https://docs.astro.build/en/reference/cli-reference/#astro-dev
    command: [
      "yarn", "run", "dev",
      "--port", "${APP_PORT:-80}",
      "--host", "0.0.0.0"
    ]

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-astro_local}"
