#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Fiber sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# The Docker services.
services:
  # The Fiber app container.
  fiber:
    # https://hub.docker.com/_/golang
    image: golang:latest
    container_name: ${APP_CONTAINER_NAME:-fiber_app}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:3000
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app/${FIBER_SAMPLE:-hello-world}
    # Start the Fiber dev Server.
    command: ["go", "run", "main.go"]

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-fiber_local}"
