#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the T3 sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# Sets the project name.
name: playground

# The Docker services.
services:
  # The t3 app container.
  t3:
    # https://hub.docker.com/_/node
    image: node:18-alpine
    container_name: ${APP_CONTAINER_NAME:-t3_app}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:${APP_PORT:-80}
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Start the t3 dev server.
    command: /bin/sh -c "yarn prisma db push && \
      yarn next telemetry disable && \
      yarn run dev -p ${APP_PORT:-80}"

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-t3_local}"
