#--------------------------------------------------------------------------
# ! The Docker Compose file is configured for local environments.
# ! Do not deploy the Jekyll sample in production environments.
#--------------------------------------------------------------------------

# Docker compose version - https://docs.docker.com/compose/compose-file
version: "3.9"

# The Docker services.
services:
  # The Jekyll app container.
  jekyll:
    # Build the Docker image from the Dockerfile.
    build:
      context: '.'
    image: jekyll:latest
    container_name: ${APP_CONTAINER_NAME:-jekyll_app}
    networks:
      - local
    # Map the app container exposed port to the host port.
    ports:
      - ${APP_PORT:-80}:${APP_PORT:-80}
      - ${API_PORT:-81}:${API_PORT:-81}
    tty: true
    volumes:
      - .${CODE_DIR:-/code}:/app
    working_dir: /app
    # Start the Jekyll CLI dev server.
    # https://jekyllrb.com/docs/configuration/options/#serve-command-options
    command: bash -c \
      "bundle install && bundle exec jekyll serve \
        --livereload \
        --host 0.0.0.0 \
        --port ${APP_PORT:-80} \
        --livereload-port ${API_PORT:-81}"

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: "${NETWORK_NAME:-jekyll_local}"
